# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fcb4fbcbd7b94ff335ffb62afc7070ba94800fc8adc79f4572f33d0131ace3e47d02db8310b0db939aba2fd0cd544afef65b0390f3e330e4ad4a7267191420c

test:
  secret_key_base: 42835486992c2304c21ad7c83b34c7cc28746d052a8c04e3b4d00b169ed53513a371f97c2f3df8ea0e6ee753c87081c1349bae43efacbd3caf34c16d6ba8de53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
